services:
  pgdatabase:
    image: postgres:latest
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - "./pgadmin_conn_data:/var/lib/pgadmin:rw"
    ports:
      - "8080:80"
